export const blockDefinitions = {
    "home-hero": { required: ["image"], arrays: ["titleParts"] },
    "services-overview": { required: ["title", "link"], arrays: ["items"] },
    "industries-showcase": { required: ["title"], arrays: ["industries", "clientLogos"] },
    "why-corvell": { required: ["title"], arrays: ["items"] },
    "guides-insights": { required: ["title"], arrays: ["guides"] },
    "about-story": { required: ["title", "image"], arrays: ["paragraphs"] },
    "firm-today": { required: ["title"], arrays: ["metrics", "credentials"] },
    "people-preview": { required: ["title", "image", "link"], arrays: ["paragraphs", "members"] },
    "page-intro": { required: ["title"] },
    "text-ticker": { arrays: ["items"] },
    "link-list-cta": { required: ["title"], arrays: ["links"] },
    "team-profiles": { required: ["title"], arrays: ["members"] },
    "team-cards": { required: ["title"], arrays: ["members"] },
    "service-category": { required: ["title"], arrays: ["cards"] },
    "labor-certification": { required: ["title"], arrays: ["steps"] },
    compliance: { required: ["title"], arrays: ["items"] },
    "action-banner": { required: ["title"] },
    "industries-hero": { required: ["image"], arrays: ["titleParts"] },
    "industry-context": { required: ["title", "image"], arrays: ["paragraphs"] },
    "industry-directory": { required: ["title"], arrays: ["industries"] },
    "industry-method": { required: ["title"], arrays: ["steps"] },
    "featured-insight": { required: ["title", "path"] },
    "insights-archive": { required: ["title"], arrays: ["items"] },
    "guide-collection": { required: ["title"], arrays: ["guides"] },
    "career-benefits": { arrays: ["benefits"] },
    "careers-roles": { required: ["title", "note"], arrays: ["items"] },
    "contact-section": { required: ["form", "details"] },
    "industry-hero": { required: ["title", "image"] },
    "industry-routes": { required: ["title"], arrays: ["items"] },
    "industry-roles": { required: ["title"], arrays: ["groups"] },
    "industry-process": { required: ["title"], arrays: ["tracks"] },
    "industry-execution": { required: ["title"], arrays: ["items"] },
    "industry-testimonial": { required: ["title", "quote"] },
    "industry-benefits": { required: ["title"], arrays: ["items"] },
    "industry-cost": { required: ["title"] },
    "industry-related": { required: ["title"], arrays: ["items"] },
    "insight-header": { required: ["title"] },
    "insight-cover": { required: ["src", "alt"] },
    "insight-stats": { arrays: ["items"] },
    content: { children: true },
    section: { children: true, flow: true },
    paragraph: { required: ["text"], flow: true },
    image: { required: ["src", "alt"], flow: true },
    table: { arrays: ["columns", "rows"], flow: true },
    aside: { required: ["text"], flow: true },
    callout: { required: ["text"], flow: true },
    list: { arrays: ["items"], flow: true },
    note: { required: ["text"], flow: true },
    timeline: { arrays: ["items"], flow: true },
    heading: { required: ["text"], flow: true },
    link: { required: ["path", "label"], flow: true },
    stats: { arrays: ["items"], flow: true }
};
